
ds1<-read.csv('d:/Workspaces/R/Apache.csv',T,sep=',')
ds2<-read.csv('d:/Workspaces/R/LLVM.csv',T,sep=',')
ds3<-read.csv('d:/Workspaces/R/X264.csv',T,sep=',')
ds4<-read.csv('d:/Workspaces/R/BDBC.csv',T,sep=',')
ds5<-read.csv('d:/Workspaces/R/BDBJ.csv',T,sep=',')
ds6<-read.csv('d:/Workspaces/R/SQLite.csv',T,sep=',')

pdf("d:/Workspaces/R/FRateoutlineT.pdf")
boxplot(ds4, boxwex=0.15, at=(1:4), outline=TRUE, names=(c("4", "4", "4", "4")),col=("green"))
boxplot(ds5, add=T, boxwex=0.15, at=(1:4)+0.15,outline=TRUE, names=(c("5", "5", "5", "5")),col=("yellow"))
boxplot(ds6, add=T, boxwex=0.15, at=(1:4)+0.3,outline=TRUE,  names=(c("6", "6", "6", "6")),col=("magenta"))
boxplot(ds1, add=T, boxwex=0.15, at=(1:4)-0.45,outline=TRUE, names=(c("1", "1", "1", "1")),col=("red"))
boxplot(ds2, add=T, boxwex=0.15, at=(1:4)-0.3,outline=TRUE,  names=(c("2", "2", "2", "2")),col=("cyan"))
boxplot(ds3, add=T, boxwex=0.15, at=(1:4)-0.15,outline=TRUE, names=(c("3", "3", "3", "3")),col=("blue"))
grid(nx=NA,ny=NULL,col="gray",lty="dashed")
mtext("Fault Rate (x100%)", side = 2, line = 2.2)
mtext(side =1, line =2.2, text=c("N","2*N", "3*N", "M"), at=(1:4)-0.07)
dev.off()


pdf("d:/Workspaces/R/FRateoutlineF.pdf")
boxplot(ds4, boxwex=0.15, at=(1:4), ylim=c(0, 0.8), outline=FALSE, names=(c("4", "4", "4", "4")),col=("green"))
boxplot(ds5, add=T, boxwex=0.15, at=(1:4)+0.15,outline=FALSE, names=(c("5", "5", "5", "5")),col=("yellow"))
boxplot(ds6, add=T, boxwex=0.15, at=(1:4)+0.3,outline=FALSE, names=(c("6", "6", "6", "6")),col=("magenta"))
boxplot(ds1, add=T, boxwex=0.15, at=(1:4)-0.45,outline=FALSE, names=(c("1", "1", "1", "1")),col=("red"))
boxplot(ds2, add=T, boxwex=0.15, at=(1:4)-0.3,outline=FALSE, names=(c("2", "2", "2", "2")),col=("cyan"))
boxplot(ds3, add=T, boxwex=0.15, at=(1:4)-0.15,outline=FALSE, names=(c("3", "3", "3", "3")),col=("blue"))
grid(nx=NA,ny=NULL,col="gray",lty="dashed")
mtext("Fault Rate (x100%)", side = 2, line = 2.2)
mtext(side =1, line =2.2, text=c("N","2*N", "3*N", "M"), at=(1:4)-0.07)
dev.off()